version: '3.2'
services:
  nginx:
    container_name: ds_rstudio_nginx
    image: "nginx:alpine"
    ports:
      - 8787:8787
    volumes:
      - /etc/dsqp/auth/:/etc/nginx/conf.d
      - /etc/dsqp/auth/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
    - rstudio
  rstudio:
    image: ds_analysis:latest
    container_name: ds_rstudio
    environment:
    - RSTUDIO_USERS=${RSTUDIO_USERS} # define users to be created <user>,<pw>;<user>,<pw>;
    volumes:
      - ${QP_DATA_DIR}/ds_scripts/:/home/
    networks:
    - rstudio
    command: bash -c "/startRServer.sh" 
networks:
  rstudio:
