version: '3.5'
services:
  opal:
    container_name: datashield_opal
    image: ds_opal:latest
    ports:
    - "443:8443"
    networks:
    - opal_net
    environment:
    - OPAL_ADMINISTRATOR_PASSWORD=${OPAL_ADMIN_PASS}
    - RSERVER_PORT_6312_TCP_ADDR=${R_SERVER_HOST}
    - MONGODBHOST=${OPAL_MONGODB_HOST}
    - INITTESTDATA=true
    volumes:
    - ${QP_DATA_DIR}/opal:/srv
    - /etc/dsqp/auth:/auth
    - /etc/dsqp/miracum_users:/miracum_users
  rserver:
    container_name: datashield_rserver
    image: obiba/opal-rserver:latest
    networks:
    - opal_net
  mongo:
    container_name: datashield_mongo
    image: mongo
    volumes:
    - ${QP_DATA_DIR}/mongo_data:/data/db
    networks:
    - opal_net
  #poll_gui_server:
   # container_name: poll_gui_server
    #restart: unless-stopped
    #image: ds_poll_gui
    #environment:
    #- OPAL_SERVER_IP=${OPAL_SERVER_IP}
    #ports:
    #  - "8443:443"
    #networks:
    # - opal_net
    #volumes:
    # - ./auth/opalcert.pem:/etc/nginx/conf.d/pollcert.pem
    # - ./auth/opalkey.pem:/etc/nginx/conf.d/pollkey.pem
  poll_server:
    container_name: poll_server
    image: ds_poll
    restart: unless-stopped
    networks:
      - opal_net
    volumes:
      - ${QP_DATA_DIR}/poll_logging:/root/ds_poll/logging
      - ${QP_CONFIG_DIR}/auth:/auth

networks:
  opal_net:
    name: ds_opal_opal_net
