version: '2.0'

services:

  queue_server:
    container_name: queue_server_prod
    image: ds_queue:latest
    volumes:
      - ./auth/queue.pem:/root/ds_queue/cert/do_cert/queue.pem
      - ./auth/queuecacert.pem:/root/ds_queue/cert/do_cert/queuecacert.pem
    environment:
    - TIMEOUT_QUEUE_AND_POLL=${TIMEOUT_QUEUE_AND_POLL} # define timeout for requests
    - ALLOWED_IPS=${ALLOWED_IPS} # ALLOWED_IPS='-c 103.102.323.23'
    - LOG_LEVEL='-l 1' # define log level
    ports:
      - "443:443"

